version: "3.8"

services:
  ql-server:
    build: .
    container_name: quake_server
    volumes:
      - ./ql:/ql
      - ./minqlx:/minqlx
    ports:
      - "27960:27960/udp"
      - "28960:28960/tcp"
    depends_on:
      - redis
    environment:
      - QL_NET_PORT=27960
      - QL_RCON_PASSWORD=strong_rcon_pass
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: quake_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
